using RustMapsApi.V4.Models;

namespace RustMapsApi.V4.Assets;

/// <summary>The single source of truth mapping each icon-bearing
/// <see cref="MonumentType"/> to its RustMaps CDN asset base name.</summary>
internal static class MonumentAssetMap
{
    /// <summary>Maps a <see cref="MonumentType"/> to its asset base name. Types absent from this
    /// map have no published icon (terrain features and the Unknown/NotImplemented/CustomMonument
    /// sentinels).</summary>
    internal static readonly IReadOnlyDictionary<MonumentType, string> AssetNames =
        new Dictionary<MonumentType, string>
        {
            [MonumentType.Gasstation] = "Gasstation",
            [MonumentType.Supermarket] = "Supermarket",
            [MonumentType.Warehouse] = "Warehouse",
            [MonumentType.Lighthouse] = "Lighthouse",
            [MonumentType.HarborSmall] = "Harbor",
            [MonumentType.HarborLarge] = "Harbor",
            [MonumentType.Airfield] = "Airfield",
            [MonumentType.Junkyard] = "Junkyard",
            [MonumentType.LaunchSite] = "Launch_Site",
            [MonumentType.MilitaryTunnels] = "Military_Tunnels",
            [MonumentType.Powerplant] = "Powerplant",
            [MonumentType.Trainyard] = "Trainyard",
            [MonumentType.WaterTreatment] = "Water_Treatment",
            [MonumentType.SphereTank] = "Sphere_Tank",
            [MonumentType.BanditTown] = "Bandit_Town",
            [MonumentType.SewerBranch] = "Sewer_Branch",
            [MonumentType.SatelliteDish] = "Satellite_Dish",
            [MonumentType.Outpost] = "Outpost",
            [MonumentType.Excavator] = "Excavator",
            [MonumentType.SulfurQuarry] = "Sulfur_Quarry",
            [MonumentType.StoneQuarry] = "Stone_Quarry",
            [MonumentType.HqmQuarry] = "Hqm_Quarry",
            [MonumentType.OilrigLarge] = "Oilrig_Large",
            [MonumentType.OilrigSmall] = "Oilrig_Small",
            [MonumentType.FishingVillageA] = "Fishing_Village",
            [MonumentType.FishingVillageB] = "Fishing_Village",
            [MonumentType.FishingVillageC] = "Fishing_Village",
            [MonumentType.WaterWellA] = "Water_Well",
            [MonumentType.WaterWellB] = "Water_Well",
            [MonumentType.WaterWellC] = "Water_Well",
            [MonumentType.WaterWellD] = "Water_Well",
            [MonumentType.WaterWellE] = "Water_Well",
            [MonumentType.SwampA] = "Swamp",
            [MonumentType.SwampB] = "Swamp",
            [MonumentType.SwampC] = "Swamp",
            [MonumentType.CaveLargeHard] = "Cave",
            [MonumentType.CaveLargeMedium] = "Cave",
            [MonumentType.CaveLargeSewersHard] = "Cave",
            [MonumentType.CaveMediumEasy] = "Cave",
            [MonumentType.CaveMediumHard] = "Cave",
            [MonumentType.CaveMediumMedium] = "Cave",
            [MonumentType.CaveSmallEasy] = "Cave",
            [MonumentType.CaveSmallHard] = "Cave",
            [MonumentType.CaveSmallMedium] = "Cave",
            [MonumentType.Iceberg1] = "Iceberg",
            [MonumentType.Iceberg2] = "Iceberg",
            [MonumentType.Iceberg3] = "Iceberg",
            [MonumentType.Iceberg4] = "Iceberg",
            [MonumentType.Iceberg5] = "Iceberg",
            [MonumentType.PowerlineA] = "Powerline",
            [MonumentType.PowerlineB] = "Powerline",
            [MonumentType.PowerlineC] = "Powerline",
            [MonumentType.PowerlineD] = "Powerline",
            [MonumentType.PowerSubstationSmall1] = "Power_Substation",
            [MonumentType.PowerSubstationSmall2] = "Power_Substation",
            [MonumentType.PowerSubstationBig2] = "Power_Substation",
            [MonumentType.PowerSubstationBig1] = "Power_Substation",
            [MonumentType.StablesA] = "Large_Barn",
            [MonumentType.StablesB] = "Large_Barn",
            [MonumentType.TunnelEntrance] = "Tunnel_Entrance",
            [MonumentType.UnderwaterA] = "Underwater_Lab",
            [MonumentType.UnderwaterB] = "Underwater_Lab",
            [MonumentType.UnderwaterC] = "Underwater_Lab",
            [MonumentType.UnderwaterD] = "Underwater_Lab",
            [MonumentType.MilitaryBaseA] = "Military_Base",
            [MonumentType.MilitaryBaseB] = "Military_Base",
            [MonumentType.MilitaryBaseC] = "Military_Base",
            [MonumentType.MilitaryBaseD] = "Military_Base",
            [MonumentType.ArcticResearchBaseA] = "Arctic_Research_Base",
            [MonumentType.NuclearMissileSilo] = "Nuclear_Missile_Silo",
            [MonumentType.FerryTerminal1] = "Ferry_Terminal_1",
            [MonumentType.TunnelEntranceTransition] = "Tunnel_Entrance_Transition",
            [MonumentType.Radtown] = "Radtown",
            [MonumentType.JungleRuinA] = "Jungle_Ruin",
            [MonumentType.JungleRuinB] = "Jungle_Ruin",
            [MonumentType.JungleRuinC] = "Jungle_Ruin",
            [MonumentType.JungleRuinD] = "Jungle_Ruin",
            [MonumentType.JungleRuinE] = "Jungle_Ruin",
            [MonumentType.JungleZigguratA] = "Ziggurat",
            [MonumentType.ApartmentsComplex] = "Apartments_Complex",
        };
}
